version: "3.6"
services:
    co_web: #
      build: . #
      volumes:
        - .:/var/www/html
      ports:
        - 2000:80

    mariadb:
      image: mariadb
      container_name: maria_projet1
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQLDATABASE=bdd_projet1

    pma:
      image: phpmyadmin/phpmyadmin
      container_name: pma_projet1
      environment:
        - PMA_HOST=mariadb
      ports:
        - 1030:80
      depends_on: 
        - mariadb 
        
    mlhog:
      image: mailhog/mailhog
      container_name: mailhog_projet1
      restart: always
      ports:        
        - 1025:1025 #smtp
        - 8025:8025 #web
      depends_on:
        - mariadb
